[package]
name = "one-brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[dependencies]
anyhow = "1.0"
crossbeam = "0.8"
heapless = "0.8"
memmap2= "0.9"
